### ISSUE TITLE
Bad case

### ISSUE THREAD

**Issue by shenzy08** [KU-CVLAB/3DFuse#11]
It is interesting to leverage depth injector and LoRA for better 3D consistency, and I get a good result with the given prompt "cute small corgi". 
However, when evaluating the prompt "a ladybug", I get rather strange results:

https://user-images.githubusercontent.com/58035336/230842387-fe5895ad-6bc1-4c29-b71c-e510758b4b6e.mp4

The generated initial images are as follows:
![instance0](https://user-images.githubusercontent.com/58035336/230842570-4e2e9351-100f-43ef-b8ec-344a9481b2d0.png)
![instance1](https://user-images.githubusercontent.com/58035336/230842586-f666b6db-ba5d-42da-9238-24834a4d9e4b.png)
![instance2](https://user-images.githubusercontent.com/58035336/230842596-a9953cf8-377e-4f85-810a-52139cfd71ff.png)
![instance3](https://user-images.githubusercontent.com/58035336/230842611-7b28ddfb-a25b-4a0e-9aa6-05c6dd4bb9e3.png)

Is it the expected results? Can you offer some advice to address the problem? Thank you!

**Comment by j0seo** [comment]
Thank you for your interest in our work! Unfortunately, there are some failure cases, many of which are due to point cloud inference models (while using an off-the-shelf point cloud model as a 3D prior is still more robust than simply determining a 3D shape through 2D prior only)

Upon watching the uploaded video, we suspect that the inferred point cloud from Point-E may have caused the creation of multiple ladybugs. Here are some potential solutions:

1) Did you use the 'base1B' version of Point-E's base model? We mistakenly set a smaller size model as the default in the first release of the code, but the latest commit covers this.
2) You can easily check where these failure cases originate from by running "gradio_demo.py".

**Comment by shenzy08** [comment]
I updated the base model to the 1B version, but the upsample model is 40M version. Is it right?
![point-e](https://user-images.githubusercontent.com/58035336/230890666-d34bdc32-b2fc-4d47-be02-c4882353f591.png)
Unfortunately, multiple ladybugs still exist after the update.

**Comment by j0seo** [comment]
It seems that Point-E failed to infer the point cloud at that seed, unfortunately. Although the seed may not be the same, the result generated from the image you provided is as follows:
![Screenshot 2023-04-10 at 7 07 10 PM](https://user-images.githubusercontent.com/41941663/230891941-ad1ac952-8e4e-456a-8f6c-f38d3095e485.png)

https://user-images.githubusercontent.com/41941663/230892030-c72ad360-0bd5-42fa-8b33-162449776fd5.mp4

If there are any updates regarding this, I'll let you know here.

**Comment by shenzy08** [comment]
Oh, it is an awesome result, I will download the updated repo and try again. Thank you!
Now I have another question about the setting of the prompt and the initial. To be specific, if I set the prompt as "a cat riding a bike" and the initial as "cat", I will get 4 images from the prompt "a cat riding a bike", and these images are employed to train a LoRA. As a result, the placeholder <0> essentially related to the prompt "a cat riding a bike". In this case, the prompt becomes "a <0> riding a bike", where  "riding a bike" seems redundant. Is that so or I misunderstand something?

**Comment by j0seo** [comment]
You're right, <0> can be considered indirectly redundant since it is related to the image generated based on the prompt. When the optimization step for the embedding was large, these things didn't have a significant impact, and as the number of steps decreased, the current approach seemed to produce slightly better results, as I remember.
