### ISSUE TITLE
Generation speed?

### ISSUE THREAD

**Issue by Jainam213** [KU-CVLAB/3DFuse#2]
Hey there! Awsome work on the paper !

I dont think I could find how much  generation speed this model takes per prompt...
If you could provide the time taken and the gpu used that would be amazing!

**Comment by j0seo** [comment]
Hi. It takes about 30-40 minutes on a desktop with a single RTX 3090, which is faster than Stable-DreamFusion (about 50 mins) and slower than SJC (about 20-30 mins). This is due to the additional burden in the depth projection process using Pytorch3D (10 mins) and about 10 mins for pivotal tuning. However, we expect to be able to reduce this after tuning the code.
