### ISSUE TITLE
gradio app not working

### ISSUE THREAD

**Issue by nagolinc** [KU-CVLAB/3DFuse#6]
This line is producing an error for me:

https://github.com/KU-CVLAB/3DFuse/blob/main/gradio_app.py#L210

to fix it added

mask=mask[:,:,3]

immediately before it

**Comment by j0seo** [comment]
Did you install carvekit directly through "pip install carvekit" instead of using the forked version (https://github.com/Ir1d/image-background-remove-tool) specified in requirement.txt.

I suspect that may cause the issue. If so, I will update the code to ensure compatibility with both versions. Thanks!

**Comment by nagolinc** [comment]
yeah, I think that was the issue. thanks!
